/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkincareRouteImport } from './routes/skincare'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HaircareRouteImport } from './routes/haircare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BridalRouteImport } from './routes/bridal'
import { Route as BodycareRouteImport } from './routes/bodycare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SkincareRoute = SkincareRouteImport.update({
  id: '/skincare',
  path: '/skincare',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HaircareRoute = HaircareRouteImport.update({
  id: '/haircare',
  path: '/haircare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalRoute = BridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const BodycareRoute = BodycareRouteImport.update({
  id: '/bodycare',
  path: '/bodycare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bodycare': typeof BodycareRoute
  '/bridal': typeof BridalRoute
  '/contact': typeof ContactRoute
  '/haircare': typeof HaircareRoute
  '/locations': typeof LocationsRoute
  '/pricing': typeof PricingRoute
  '/skincare': typeof SkincareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bodycare': typeof BodycareRoute
  '/bridal': typeof BridalRoute
  '/contact': typeof ContactRoute
  '/haircare': typeof HaircareRoute
  '/locations': typeof LocationsRoute
  '/pricing': typeof PricingRoute
  '/skincare': typeof SkincareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bodycare': typeof BodycareRoute
  '/bridal': typeof BridalRoute
  '/contact': typeof ContactRoute
  '/haircare': typeof HaircareRoute
  '/locations': typeof LocationsRoute
  '/pricing': typeof PricingRoute
  '/skincare': typeof SkincareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bodycare'
    | '/bridal'
    | '/contact'
    | '/haircare'
    | '/locations'
    | '/pricing'
    | '/skincare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bodycare'
    | '/bridal'
    | '/contact'
    | '/haircare'
    | '/locations'
    | '/pricing'
    | '/skincare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bodycare'
    | '/bridal'
    | '/contact'
    | '/haircare'
    | '/locations'
    | '/pricing'
    | '/skincare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BodycareRoute: typeof BodycareRoute
  BridalRoute: typeof BridalRoute
  ContactRoute: typeof ContactRoute
  HaircareRoute: typeof HaircareRoute
  LocationsRoute: typeof LocationsRoute
  PricingRoute: typeof PricingRoute
  SkincareRoute: typeof SkincareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skincare': {
      id: '/skincare'
      path: '/skincare'
      fullPath: '/skincare'
      preLoaderRoute: typeof SkincareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haircare': {
      id: '/haircare'
      path: '/haircare'
      fullPath: '/haircare'
      preLoaderRoute: typeof HaircareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal': {
      id: '/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof BridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodycare': {
      id: '/bodycare'
      path: '/bodycare'
      fullPath: '/bodycare'
      preLoaderRoute: typeof BodycareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BodycareRoute: BodycareRoute,
  BridalRoute: BridalRoute,
  ContactRoute: ContactRoute,
  HaircareRoute: HaircareRoute,
  LocationsRoute: LocationsRoute,
  PricingRoute: PricingRoute,
  SkincareRoute: SkincareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
